name: Uptown I.T. Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      placeholder: mrpoophead@poopyheads-r-us.com

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the issue
    validations:
      required: true

  - type: dropdown
    id: issue
    attributes:
      label: Issue
      options:
        - No communications
        - That's a questions
        - Unclear questions
        - Increasement
    validations:
      required: true